# Update python package at https://pypi.org/project/ceph-nvmeof/
name: Upload release to PyPI
on:
  push:
    tags:
      - '*'
    branches:
      - 'test'

jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: pdm-project/setup-pdm@v3
        with:
          python-version: 3.9
          version: "2.7.4"
      # - name: Install wheel
      #   run: pip3 add wheel
      - name: Sync Dependencies 
        run: pdm "sync" -v --no-isolation --no-self --no-editable
      - name: Compile Protocol Buffers
        run: pdm run protoc
      - name: Publish package distributions to PyPI
        run: pdm publish
